
export const defaultFormValues = {
  title: "",
  description: "",
  category: "",
  location: "",
  locationType: "inPerson",
  address: "",
  city: "",
  state: "",
  zipCode: "",
  onlineLink: "",
  classDetails: "",
  difficultyLevel: "beginner",
  price: "",
  capacity: "",
  minParticipants: 1,
  maxParticipants: 10,
  images: [] as File[],
  scheduleType: "oneTime",
  startDate: "",
  endDate: "",
  startTime: "",
  endTime: "",
  recurringDays: [] as string[],
  whatToBring: [] as string[],
  learningOutcomes: [] as string[],
};

export const formSteps = [
  { id: "basic-info", label: "Basic Info" },
  { id: "location-category", label: "Location & Category" },
  { id: "details", label: "Details" },
  { id: "pricing", label: "Pricing & Capacity" },
  { id: "images", label: "Images" },
  { id: "schedule", label: "Schedule" },
  { id: "bring-items", label: "Items to Bring" },
  { id: "learning", label: "Learning Outcomes" },
];
