// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pylbrdwuikhwupqjcqzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5bGJyZHd1aWtod3VwcWpjcXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczODE0NjIsImV4cCI6MjA1Mjk1NzQ2Mn0.wv0brXcxcaxE5ssTWOaXTeOCQxnH1m-K7botOCh8Vbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);